{% set name = "yosys" %}
{% set version = "0.39" %}
{% set sha256 = "a66d95747b21d03e5b9c274d3f7cb0f7dd99610891dd66920bfaee25bc30dad1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/YosysHQ/{{ name }}/archive/refs/tags/yosys-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bison
    - make
    - pkg-config
  host:
    - compilers
    - libboost-python-devel
    - flex
    - libffi
    - libzlib
    - readline
    - tk
    - zlib
  run:
    - graphviz
    - libffi
    - libzlib
    - readline
    - tk

test:
  commands:
    - yosys-config --prefix
    - yosys-config --ldflags

about:
  home: https://github.com/YosysHQ/yosys
  license: ISC
  license_family: OTHER
  license_file: COPYING
  summary: Yosys Open SYnthesis Suite
  description: |
    This is a framework for RTL synthesis tools. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.
  dev_url: https://github.com/YosysHQ/yosys

extra:
  recipe-maintainers:
    - whitequark
    - timkpaine
